### ISSUE TITLE
Feature Request(Low Priority): Rename Overlays in the Management List

### ISSUE THREAD

**Issue by 42nfl19** [elvissteinjr/DesktopPlus#12]
Either I am blind or dumb but I could not find a way to rename Overlays in Desktop+. This would be very helpful for me and others when organizing multiple overlays. And it would be useful when creating a new overlay and I want it to have the same starting parameters as another overlay before making minor edits. What I usually end up having to do is to slowly mouse over all my overlays and see which one in my vision highlights blue.

**Comment by elvissteinjr** [comment]
It's kind of hidden of but mentioned in the readme:  You can right click the drop-down selection to edit the name of the current overlay.
I suppose another button in the management popup could be added as well if that seems useful.

**Comment by 42nfl19** [comment]
Thanks for the advice! No wonder I could not find anything. Though based on reading the readme, it would take additional steps of being in desktop mode. Can't really right click in VR. Having a button would be very useful so that you would not have to move back and forth when fiddling with multiple properties.

**Comment by elvissteinjr** [comment]
Oh you can right-click in VR, that's not a problem. By default this should be on the touchpad if you have one on your controllers, otherwise check whatever is bound in the VR Dashboard input bindings for the laser pointer mouse buttons. I've not really been successful in retrieving the input source names for these bindings so the interface refers to them as the action they're bound to (so mouse buttons).
It's the same way you right-click on the desktop overlays themselves. Or have you never done that?

I'll see to get an additional renaming button going before the next build. This isn't terribly difficult to add after all.
Is there a reason you've not updated to the latest stable build? There _should_ be no downsides to it, at least none I've been made aware of yet.

**Comment by 42nfl19** [comment]
Huh, I have right clicked in the overlay in my desktop before. Maybe it is because when I go into the settings, my mind thinks that this UI/"overlay" is a VR thing therefore it does not have the normaties that you normaly have with a KB+M on a desktop.

Also the reason I have not been update is that since I DL from github, I forget or normally don't check to see if there is an update. I did not even know there was a Steam release until today. At least now when I finally transfer to the steam version, it should auto update....unless the github release had an auto update that I missed lol. I mean there probably is a thing with github itself that auto downloads the releases.

**Comment by elvissteinjr** [comment]
Starting with v2.3.5 Beta, there's an additional rename button in the overlay management popup. Closing this.
