### ISSUE TITLE
Performance Monitor causes stutter/frametime spikes with nvidia GPU

### ISSUE THREAD

**Issue by zmz125000** [elvissteinjr/DesktopPlus#15]
461.40 Driver Release Notes

`[Steam VR game]: Stuttering and lagging occur upon launching a game (without running running any GPU hardware monitoring tool in the background) [3152190]`

As shown by fpsVR with Desktop+ running all VR games has frametime spikes, disable Desktop+ no spike. It's easily reproducible.

In recent fpsVR update an option was added to disable monitoring

`The fpsVR has been updated with the following changes:
Added setting "GPU Monitoring Interval" (on the "fpsVR" tab in settings). Allows to select one of the values: "500 ms", "1000 ms", "2000 ms", "Disable Monitoring".`

Thanks

**Comment by elvissteinjr** [comment]
To clarify, do the spikes appear just from having Desktop+ running or when the Performance Monitor is visible?
I'm aware of the latter, but hoped it would only happen while it's visible since the performance data is not updated when the Performance Monitor is not visible (related query handles are kept open however).
Personally I've been avoiding updating my GPU driver ever since the stutters initially came up, so I just hoped nvidia would fix their stuff before I had to really care. I know 3000 series users can't avoid using those drivers, though.

I'll make necessary changes to not have any GPU performance queries open when not requested or needed. Until then I'd recommend using an older build (v2.3.3 is the last without it) if the spikes ruin the experience.

**Comment by zmz125000** [comment]
I didn't know desktop+ has Performance Monitor before today, and using v2.3.3 fixes it so it would be "the spikes appear just from having Desktop+ running".
Spikes make image freeze for a few milliseconds, it definitely ruine experience.
@elvissteinjr

**Comment by elvissteinjr** [comment]
This has been resolved in v2.4.3 Beta. 
Performance counters will not be active at all when the Performance Monitor is not visible now and there's also a new option to explicitly disable GPU-related performance counters to avoid those stutters altogether (will probably be removed again once truly fixed drivers exist).

Let me know if there are still issues with this.
