### ISSUE TITLE
Keyboard button has to be pressed twice for the keyboard to open

### ISSUE THREAD

**Issue by matejdro** [elvissteinjr/DesktopPlus#29]
I found a pretty annoying bug in the NewUI Preview build:

Whenever I press open keyboard button, nothing happens. I have to press the button the second time for the keyboard to actually open.

**Comment by elvissteinjr** [comment]
Thanks for the report. This one has actually been on my list already and will be fixed in the next build (along with a good bunch of other keyboard related improvements).
I believe last time I checked this happens only when the keyboard had disappeared from the dashboard being closed... unless my notes are incorrect, that is.

Either way, I'll get it sorted out, thanks.

**Comment by elvissteinjr** [comment]
Fix now available in NewUI Preview 3.

**Comment by matejdro** [comment]
Confirmed works, thanks!
