### ISSUE TITLE
Add an option to allow for touch controls like oculus link or virtual desktop does

### ISSUE THREAD

**Issue by EmergencyTemporalShift** [elvissteinjr/DesktopPlus#74]
Using the current controls can feel a bit clunky to scroll. The text just highlights. I assume they are touch controls because that's what they look like when you hold click in other programs (it makes a box and right clicks)

**Comment by elvissteinjr** [comment]
I've added an option to simulate laser pointer mouse input as pen input (on new-ui branch). Should be mostly equivalent to simulating touch inputs, but still allows for secondary button presses before falling back to mouse buttons, so I went with that.

Some of the functionality, such as hold to right-click, is controlled by Windows settings for pen input. If something seems off it's worth checking there as well. Threw me off during testing once at least.

If you want to check it out right away, there's automated builds now too.
I'll close this since it seems to be working fine on my end, but feel free to re-open if something's wrong with it.
