### ISSUE TITLE
是否有增加多语言计划，比如中文

### ISSUE THREAD

**Issue by kpsmail** [elvissteinjr/DesktopPlus#75]
是否有增加多语言计划，比如中文

**Comment by elvissteinjr** [comment]
I would prefer if you used English for this type of communication. I end up having to use machine translation for Chinese anyways and it makes it easier for anyone else to read what is happening here.

For the question itself: Future versions will have support for different languages. Right now, the NewUI branch with the preview builds features German and Japanese in addition to English.
However, since I only speak English and German, I'm relying on community translations for everything else. Chinese would be a welcome addition of course. 
At the same time, as many things are still changing before the new UI gets to be the default stable build. I wouldn't recommend making one right now (but as it happened with Japanese, I'll likely add it anyways if offered).
I was planning to ask for translations a little bit later so they wouldn't have to be updated too often and be complete for the initial release of the new UI.

But even without my involvement, for the NewUI branch the languages files are separated plain text files and can be edited and shared as you see fit.
